version: '3.8'

services:
  rust-android-dev:
    image: gaikwadabhi1999/new-rust-android # Update image name and tag
    container_name: rust-android-dev-container
    environment:
      - ANDROID_HOME=/opt/android-sdk
    volumes:
      - .:/workspace
    ports:
      - "8081:8080"  # Example port forwarding, adjust as needed
    stdin_open: true
    tty: true
    command: /bash
